### ISSUE TITLE
Error when uploading project from local folder

### ISSUE THREAD

**Issue by jesselangdon** [Riverscapes/RiverscapesToolbar#8]
I attempted to upload a local 'solar' project folder (C:\JL\Projects\solar\UpperSalmon\Riverscapes), but received this error after clicking the upload button:

![upload_error](https://user-images.githubusercontent.com/2524993/27206197-ad15e55a-51ea-11e7-9060-ec89399fffad.png)

```
Traceback (most recent call last):
			  File "C:/Users/jlangdon/.qgis2/python/plugins\RiverscapesToolbar\RiverscapesToolbar\DWTabProject.py", line 60, in projectUpload
			    dialog = AddQueueDialog(S3Operation.Direction.UP, DockWidgetTabProject.project)
			  File "C:/Users/jlangdon/.qgis2/python/plugins\RiverscapesToolbar\RiverscapesToolbar\AddQueueDialog.py", line 53, in __init__
			    self.qItem = QueueItem(self.project, conf)
			  File "C:/Users/jlangdon/.qgis2/python/plugins\RiverscapesToolbar\RiverscapesToolbar\DWTabDownload.py", line 147, in __init__
			    self.opstore = s3BuildOps(self.conf, self.updateTransferProgress)
			  File "C:/Users/jlangdon/.qgis2/python/plugins\RiverscapesToolbar\RiverscapesToolbar\lib\s3\walkers.py", line 35, in s3BuildOps
			    localProductWalker(conf.localroot, files)
			  File "C:/Users/jlangdon/.qgis2/python/plugins\RiverscapesToolbar\RiverscapesToolbar\lib\s3\walkers.py", line 75, in localProductWalker
			    localProductWalker(projroot, filedict, relpath)
			  File "C:/Users/jlangdon/.qgis2/python/plugins\RiverscapesToolbar\RiverscapesToolbar\lib\s3\walkers.py", line 75, in localProductWalker
			    localProductWalker(projroot, filedict, relpath)
			  File "C:/Users/jlangdon/.qgis2/python/plugins\RiverscapesToolbar\RiverscapesToolbar\lib\s3\walkers.py", line 75, in localProductWalker
			    localProductWalker(projroot, filedict, relpath)
			  File "C:/Users/jlangdon/.qgis2/python/plugins\RiverscapesToolbar\RiverscapesToolbar\lib\s3\walkers.py", line 75, in localProductWalker
			    localProductWalker(projroot, filedict, relpath)
			  File "C:/Users/jlangdon/.qgis2/python/plugins\RiverscapesToolbar\RiverscapesToolbar\lib\s3\walkers.py", line 71, in localProductWalker
			    print spaces + relpath
			IOError: [Errno 9] Bad file descriptor
```

**Comment by MattReimer** [comment]
Cool. thanks for trying this. I'm on it.

**Comment by MattReimer** [comment]
Wow @jesselangdon this was a good find and pretty scary. Essentially it would've let anyone upload anything to any place in the repo. Really glad you caught it.
